### ISSUE TITLE
Worker Deployment Error

### ISSUE THREAD

**Issue by TugT4G** [samouri/amp-cloudflare-optimizer#3]
Hi,

So I have been trying to Deploy with Workers to my Cloudflare account and for some reason, there is an error.

The Link the Deploy with Workers form has listed is [https://github.com/ampproject/cloudflare-amp-optimizer](https://github.com/ampproject/cloudflare-amp-optimizer).

I purchased the Cloudflare Worker plan for $5 to deploy Workers Unbound and followed the instructions:

1. I added our domain to the config.json file via the forked repository.
2. I authorized GitHub with Workers. First, the link led me to a list of other workers and none listed were the current one. I went back then clicked on the link again as I could not continue. This option leads to an Error 1101 with the URL as [https://deploy.workers.cloudflare.com/login](https://deploy.workers.cloudflare.com/login). To move on to the next step I had to go back to the form and refresh the page.
3. I then Configured my Cloudflare Account.
4. Via Deploy with GitHub Actions, I clicked on Fork the Repository. Then, I clicked the link to Enable GitHub Actions and the URL leads to a 404 - [http://github.com/undefined/actions](http://github.com/undefined/actions). 
6. It started initialization but failed and says "error".

I am not sure if there is an issue with the application or an error on my end. Any help would be greatly appreciated!

Thanks and regards,

Tug

**Comment by samouri** [comment]
Hi Tug,

I'm sorry that you've stumbled on this repo which was not intended to ever actually be used!
It was a playground for me while prototyping running the AMP Optimizer within a Cloudflare Worker.  I'll update the README.md to indicate such.

Please check out this repo instead for the real thing: https://github.com/ampproject/cloudflare-amp-optimizer.

I'm going to close this issue and archive the repository. Please let me know if you have issues with the `ampproject/cloudflare-amp-optimizer` package and open an issue there instead :) 

Best,
Jake
